// nomenclador.js
// Códigos de faltas BMZCN
// Generado a partir de la lista provista por el usuario.

const NOMENCLADOR_CODIGOS = {
  "1089": { codigo: "1089", referencia: "sobrepaso o intento indebido" },
  "2016": { codigo: "2016", referencia: "Alcoholemia" },
  "2020": { codigo: "2020", referencia: "Alcoholemia" },
  "2033": { codigo: "2033", referencia: "Alcoholemia Profesional" },
  "2047": { codigo: "2047", referencia: "estupefacientes/aptitud" },
  "2050": { codigo: "2050", referencia: "negarse a alcoholemia" },
  "3018": { codigo: "3018", referencia: "Por circular en carril izquierdo" },
  "3021": { codigo: "3021", referencia: "giro antirreglamentario" },
  "3048": { codigo: "3048", referencia: "obstrucción transversal por inobservancia" },
  "3052": { codigo: "3052", referencia: "giro sin respetar semáforo" },
  "3065": { codigo: "3065", referencia: "Por no respetar reglas multicarril" },
  "3079": { codigo: "3079", referencia: "Luces apagadas" },
  "3082": { codigo: "3082", referencia: "circular a contramano o sobre banquina" },
  "3096": { codigo: "3096", referencia: "frenado brusco o maniobras intempestivas" },
  "3110": { codigo: "3110", referencia: "Obstruir Bocacalle por inobservancia" },
  "3124": { codigo: "3124", referencia: "No respetar distancia entre vehículos" },
  "3137": { codigo: "3137", referencia: "Circular marcha atrás" },
  "3141": { codigo: "3141", referencia: "detenerse o estacionarse en banquina" },
  "3154": { codigo: "3154", referencia: "sobrepaso indebido" },
  "3168": { codigo: "3168", referencia: "cruzar vía cuando aproxima tren" },
  "3171": { codigo: "3171", referencia: "No respetar distancia entre camión y colectivos" },
  "3185": { codigo: "3185", referencia: "vehículo sin fin de trasportar que transporta a granel" },
  "3198": { codigo: "3198", referencia: "llevar elemento que afecta visibilidad o seguridad o sobresalga los limites" },
  "3209": { codigo: "3209", referencia: "Por usar bocina cuando no corresponde" },
  "3213": { codigo: "3213", referencia: "conducción con celular  o elementos similares" },
  "3226": { codigo: "3226", referencia: "Emisión humo, gases o contaminantes al ambiente" },
  "3230": { codigo: "3230", referencia: "Vehículo de Emergencia sin respetar normas" },
  "3243": { codigo: "3243", referencia: "Por utilizar cartel especial irregularmente" },
  "3257": { codigo: "3257", referencia: "Por no presentar documenta habiendo participado en siniestro vial" },
  "3291": { codigo: "3291", referencia: "No cumplir reglas en semi o autopistas" },
  "3302": { codigo: "3302", referencia: "Sobrepaso en curva" },
  "3315": { codigo: "3315", referencia: "Polarizado o aditamentos" },
  "3329": { codigo: "3329", referencia: "Por dejar animales sueltos" },
  "3332": { codigo: "3332", referencia: "Obstaculizar o impedir  la circulación" },
  "3346": { codigo: "3346", referencia: "vehículo detenido con emergencia sin balizas" },
  "3359": { codigo: "3359", referencia: "fuga luego de accidente" },
  "3363": { codigo: "3363", referencia: "Circular estando Legalmente inhabilitado" },
  "4036": { codigo: "4036", referencia: "caño de escape no reglamentario" },
  "4040": { codigo: "4040", referencia: "matafuego y balizas" },
  "4053": { codigo: "4053", referencia: "menores de(10) años en asiento delantero" },
  "4067": { codigo: "4067", referencia: "condiciones de seguridad" },
  "4070": { codigo: "4070", referencia: "sistemas de seguridad sin funcionar" },
  "4084": { codigo: "4084", referencia: "sin casco o bandolera reflectante" },
  "4097": { codigo: "4097", referencia: "casco sin parabrisas" },
  "4108": { codigo: "4108", referencia: "sin correaje colocados" },
  "4112": { codigo: "4112", referencia: "cubiertas lisas o con fallas" },
  "4125": { codigo: "4125", referencia: "acarreo de birrodados" },
  "4139": { codigo: "4139", referencia: "Por remolcar automotores" },
  "4142": { codigo: "4142", referencia: "Por circular con mas de un acoplado" },
  "4156": { codigo: "4156", referencia: "Reparación de vehículos sobre la calzada" },
  "4169": { codigo: "4169", referencia: "acarrear animales sobre ruta" },
  "4173": { codigo: "4173", referencia: "Puestos de ventas sobre banquina" },
  "4186": { codigo: "4186", referencia: "circular con elementos en rueda que daña calzada" },
  "4190": { codigo: "4190", referencia: "enganche , defensas o elementos sobresalientes" },
  "4201": { codigo: "4201", referencia: "pesos y dimensiones antirreglamentario" },
  "4214": { codigo: "4214", referencia: "traslado de vehículo con tacómetro sin funcionar" },
  "4228": { codigo: "4228", referencia: "sin inscripción de autopartes" },
  "4231": { codigo: "4231", referencia: "comercio de luces antirreglamentarias" },
  "4245": { codigo: "4245", referencia: "comercio de caños de escapes antirreglamentarios" },
  "5011": { codigo: "5011", referencia: "negar documentación exigible" },
  "5024": { codigo: "5024", referencia: "cédula de identificación" },
  "5038": { codigo: "5038", referencia: "sin portar comprobante de seguro" },
  "5041": { codigo: "5041", referencia: "sin seguro vigente" },
  "5055": { codigo: "5055", referencia: "No realizar transferencia" },
  "6012": { codigo: "6012", referencia: "campo con animales sin alambrados" },
  "6026": { codigo: "6026", referencia: "incumplir con servicios de comunicación y auxilio" },
  "6039": { codigo: "6039", referencia: "Por colocar carteles" },
  "6043": { codigo: "6043", referencia: "caso omiso a demarcación y señalamiento" },
  "6056": { codigo: "6056", referencia: "ejecutar obras en ruta sin aviso" },
  "6060": { codigo: "6060", referencia: "ejecutar obras sin aprobación" },
  "6073": { codigo: "6073", referencia: "obra sin señalamiento, desvíos o no cumplir plazos" },
  "6087": { codigo: "6087", referencia: "obra sin cartelería" },
  "6090": { codigo: "6090", referencia: "obra que no advierte a los usuarios" },
  "6101": { codigo: "6101", referencia: "obra que no coordine para eliminar riesgos" },
  "6115": { codigo: "6115", referencia: "obra que omite señalamiento de paso de personal y vehículos" },
  "6128": { codigo: "6128", referencia: "obra que no garantiza acceso a lugares" },
  "6132": { codigo: "6132", referencia: "persona que no permita colocación de cartelería vial" },
  "6145": { codigo: "6145", referencia: "persona lindante que coloque carteles" },
  "6159": { codigo: "6159", referencia: "poseedor lindante que no mantenga las condiciones de seguridad con la vía publica" },
  "6162": { codigo: "6162", referencia: "persona lindante que tire aguas servidas a la vía publica" },
  "6176": { codigo: "6176", referencia: "persona lindante que dejare cosas o desperdicios donde no corresponde" },
  "6189": { codigo: "6189", referencia: "poseedor lindante que su inmueble no posea balizas" },
  "6193": { codigo: "6193", referencia: "poseedor lindante que coloque anuncios sin autorización" },
  "6204": { codigo: "6204", referencia: "persona lindante que genere humo y gases que afecten la seguridad" },
  "6217": { codigo: "6217", referencia: "establecimiento industrial o comercial que genere humo o gases" },
  "6221": { codigo: "6221", referencia: "establecimiento que reincide en generación de humo y gases" },
  "6234": { codigo: "6234", referencia: "construcciones sin autorización" },
  "6248": { codigo: "6248", referencia: "construcción que discrimina desplazamiento de discapacitados" },
  "7014": { codigo: "7014", referencia: "estacionarse a media metro del cordón" },
  "7027": { codigo: "7027", referencia: "estacionamiento afectando visibilidad y/o seguridad y/o fluidez" },
  "7044": { codigo: "7044", referencia: "estacionamiento en esquinas" },
  "7058": { codigo: "7058", referencia: "estacionamiento sobre senda peatonal o ciclovía o paradas de colectivos" },
  "7061": { codigo: "7061", referencia: "estacionamiento frente a hospitales o escuela o otros servicios públicos" },
  "7075": { codigo: "7075", referencia: "estacionamiento frente a cine, teatro o similares en horas de funcionamiento" },
  "7088": { codigo: "7088", referencia: "estacionamiento en garaje de ingreso" },
  "7092": { codigo: "7092", referencia: "estacionamiento por mas de 5 días" },
  "7120": { codigo: "7120", referencia: "estacionamiento de colectivo, camión o maquinaria en lugar no permitido" },
  "7133": { codigo: "7133", referencia: "estacionamiento en zona rural y no estar lo mas lejos posible de la calzada" },
  "8015": { codigo: "8015", referencia: "peaje que no colabora con la autoridad" },
  "8029": { codigo: "8029", referencia: "peaje que impida que la autoridad haga estacionar un vehículo sancionado" },
  "8032": { codigo: "8032", referencia: "peaje que no exhibe al publico contrato de concesión" },
  "8046": { codigo: "8046", referencia: "peaje que no comunica sobre vehículos evidentemente en falta" },
  "8059": { codigo: "8059", referencia: "peaje que no comunica novedades sobre seguridad en la ruta" },
  "9017": { codigo: "9017", referencia: "Por circular sin tener edad mínima" },
  "9064": { codigo: "9064", referencia: "circular teniendo habilitación suspendida" },
  "9078": { codigo: "9078", referencia: "habilitación para esa categoría" },
  "9081": { codigo: "9081", referencia: "sin portar licencia" },
  "9095": { codigo: "9095", referencia: "persona con discapacidad sin  habilitación" },
  "9106": { codigo: "9106", referencia: "por ceder la conducción a persona no habilitada" },
  "9119": { codigo: "9119", referencia: "sin habilitación" },
  "9123": { codigo: "9123", referencia: "licencia no mas de 6 meses" },
  "9136": { codigo: "9136", referencia: "licencia mas de 6 meses" },
  "9140": { codigo: "9140", referencia: "licencia caduca" },
  "9153": { codigo: "9153", referencia: "licencia no valida" },
  "9167": { codigo: "9167", referencia: "licencia mal otorgada" },
  "10014": { codigo: "10014", referencia: "maquinaria en infracción" },
  "11029": { codigo: "11029", referencia: "sin las patentes" },
  "11032": { codigo: "11032", referencia: "patente con aditamentos tapada o alterada" },
  "11046": { codigo: "11046", referencia: "sin patente delantera o fuera de lugar" },
  "11059": { codigo: "11059", referencia: "sin patente trasera o fuera de lugar" },
  "11063": { codigo: "11063", referencia: "grabados del vehículo" },
  "12017": { codigo: "12017", referencia: "no respetar prioridad de paso" },
  "12020": { codigo: "12020", referencia: "no acatar controles y ordenes" },
  "12034": { codigo: "12034", referencia: "Por no respetar las indicaciones de la autoridad" },
  "12106": { codigo: "12106", referencia: "prioridad de paso en cuestas" },
  "12119": { codigo: "12119", referencia: "por hacer lo opuesto que indica el semáforo" },
  "12136": { codigo: "12136", referencia: "no respetar barreras de vía" },
  "12140": { codigo: "12140", referencia: "no ceder el paso al de derecha" },
  "13018": { codigo: "13018", referencia: "sin Rto vigente" },
  "13022": { codigo: "13022", referencia: "sin portar Rto" },
  "13035": { codigo: "13035", referencia: "centros de Rto no habilitado" },
  "13049": { codigo: "13049", referencia: "centros de Rto que no cumple la normativa" },
  "13052": { codigo: "13052", referencia: "centros de Rto que emite certificados defectuosos" },
  "13066": { codigo: "13066", referencia: "centros de Rto negligente que genere demoras a usuarios" },
  "13079": { codigo: "13079", referencia: "centros de Rto que no suministren información exigida" },
  "14006": { codigo: "14006", referencia: "persona que circule por calzada sin elementos retroreflectivos" },
  "14010": { codigo: "14010", referencia: "peatón que no respeta semáforos" },
  "14023": { codigo: "14023", referencia: "por realizar maniobra que pone en peligro a peatón" },
  "14037": { codigo: "14037", referencia: "por realizar maniobra que pone en peligro a menores o discapacitados" },
  "15001": { codigo: "15001", referencia: "excedido en velocidad hasta 10 km/h" },
  "15002": { codigo: "15002", referencia: "excedido en velocidad mas de 10km/h hasta 20km/h" },
  "15008": { codigo: "15008", referencia: "velocidad" },
  "15100": { codigo: "15100", referencia: "picadas" },
  "15114": { codigo: "15114", referencia: "picadas con vehículos modificados" },
  "16013": { codigo: "16013", referencia: "colocar Peloteros/realizar eventos en vía publica" },
  "17031": { codigo: "17031", referencia: "Profesionales que no circulen por derecha o con cuidado y prevención" },
  "17045": { codigo: "17045", referencia: "Profesional circulando con vehículo antiguo" },
  "17058": { codigo: "17058", referencia: "exceso en dimensiones" },
  "17062": { codigo: "17062", referencia: "exceso de peso" },
  "17075": { codigo: "17075", referencia: "sin habilitación técnica" },
  "17089": { codigo: "17089", referencia: "Por no tener circulo  de velocidad máxima" },
  "17092": { codigo: "17092", referencia: "guía" },
  "17103": { codigo: "17103", referencia: "ficha de emergencia" },
  "17117": { codigo: "17117", referencia: "cartas de portes o permisos" },
  "17120": { codigo: "17120", referencia: "transporte escolar sin medidas de seguridad" },
  "17134": { codigo: "17134", referencia: "falta de inscripción" },
  "17147": { codigo: "17147", referencia: "No portar carta de Porte" },
  "17151": { codigo: "17151", referencia: "transporte de carga" },
  "17164": { codigo: "17164", referencia: "transporte con carga que sobresale los limites" },
  "17178": { codigo: "17178", referencia: "mercancías peligrosas" },
  "17181": { codigo: "17181", referencia: "No Portar inscripción provincial" },
  "17195": { codigo: "17195", referencia: "No tener inscripción provincial" },
  "17206": { codigo: "17206", referencia: "transporte de contenedor en vehículo no adaptado" },
  "17219": { codigo: "17219", referencia: "camión playo sin cintas o cables de seguridad" },
  "17223": { codigo: "17223", referencia: "impedir revisión de carga" },
  "17236": { codigo: "17236", referencia: "permanecer en playa de puerto sin autorización de ingreso" },
  "17240": { codigo: "17240", referencia: "puerto que provee información" },
  "17253": { codigo: "17253", referencia: "negarse al ordenamiento para ingresar al puerto" },
  "18002": { codigo: "18002", referencia: "bicicletas sin reflectantes y casco" },
  "18016": { codigo: "18016", referencia: "conducción peligrosa que pone en riesgo un ciclista" },
  "18029": { codigo: "18029", referencia: "conducción peligrosa que pone en riesgo a menores o discapacitados" },
  "19004": { codigo: "19004", referencia: "incumplimiento de personal medico" },
  "19017": { codigo: "19017", referencia: "persona jurídica" },
  "19021": { codigo: "19021", referencia: "promover conductas contrarias a la ley de transito" },
  "19034": { codigo: "19034", referencia: "realizar publicidad sin permiso" },
  "19048": { codigo: "19048", referencia: "enseñanza de conducción sin cumplir requisitos" },
  "19051": { codigo: "19051", referencia: "por hacer publicidad y colocar anuncios" },
  "19065": { codigo: "19065", referencia: "por publicidad de alcohol" },
  "19078": { codigo: "19078", referencia: "publicidad" },
  "19082": { codigo: "19082", referencia: "publicidad" },
  "19095": { codigo: "19095", referencia: "señalamiento" },
};

function normalizeCodigoFalta(codigo) {
  return String(codigo || "").replace(/\D+/g, "");
}

function getNomencladorFalta(codigo) {
  const key = normalizeCodigoFalta(codigo);
  return NOMENCLADOR_CODIGOS[key] || null;
}

function getReferenciaFalta(codigo, fallback = "") {
  const item = getNomencladorFalta(codigo);
  return item ? item.referencia : fallback;
}

if (typeof window !== "undefined") {
  window.NOMENCLADOR_CODIGOS = NOMENCLADOR_CODIGOS;
  window.normalizeCodigoFalta = normalizeCodigoFalta;
  window.getNomencladorFalta = getNomencladorFalta;
  window.getReferenciaFalta = getReferenciaFalta;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    NOMENCLADOR_CODIGOS,
    normalizeCodigoFalta,
    getNomencladorFalta,
    getReferenciaFalta
  };
}
